version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: sudo pip install boto3
             echo ${BUCKET_NAME}
      - run: python3 test.py

workflows:
  build:
    jobs:
      - build
