version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout 
      - run: sudo pip install boto3
      - run: python3 test.py
             echo $BUCKET_NAME

workflows:
  build:
    jobs:
      - build
