version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node
      
    steps:
      - checkout
      - run:
          name: Sync to s3
          command: aws s3 sync dist s3://pycodeuploadbucket --acl public-read    
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
            
      - run: 
          name: Run tests with code coverage
          command: npm test --coverage
          
      - run:
          name: Deploy application 
          command: sls deploy  

      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}
